### PR TITLE
Add rotation buttons

### PR DESCRIPTION
**Pull request by Horat1us**

### CODE REVIEW

**Comment by Horat1us** [comment]
what about this feature?

**Comment by fauster01** [comment]
Confirm this please, we need it!
Thanks.
^_^

**Comment by fritz-c** [comment]
I really like what you've prepared with the icons and your code. However, I think this would be better handled outside of the lightbox, by adding custom buttons (possible) and custom style on the image elements (not currently possible). I say so for two reasons:
1. The rotation is not preserved in this implementation, so the images kind of cartwheel away.
2. The rotation of long rectangular images results in them getting cut off at the top and bottom. This is a result of how I calculate its size in the screen. It would take some modification of other parts of the component to make it fit right.

**Comment by Horat1us** [comment]
I suppose that this implementation of rotation is the only available without canvas. May be we can just disable this feature by default, until someone will give another solution?
Because I (and probably many other people) depend on this library in many projects and It will hard to do another library that wraps this.

**Comment by Horat1us** [comment]
So, should I think about creating wrapper for this library?

**Comment by Horat1us** [comment]
@fauster01 may be you should use https://github.com/Horat1us/react-image-lightbox-rotate 
There is some bugs but it may be useful for you.

**Comment by arpitprod** [comment]
how to use react-image-lightbox-rotate in react-image-lightbox
please show example code

**Pull request closed without merging**
