### PR TITLE
Replace unsafe methods

### PR DESCRIPTION
**Pull request by mmarkelov**
#196

### CODE REVIEW

**Comment by harm-meijer** [comment]
Renaming to unsafe will just delay the problem until asynchronous rendering is released.

**Comment by mmarkelov** [comment]
@harm-meijer youp! And because of it I just replaced all unsafe methods

**Comment by harm-meijer** [comment]
I was about to clone and see if it was possible to convert to hooks but if you already did this then it won't be necessary.

**Comment by avizuber** [comment]
@mmarkelov can you please fix the merge conflicts?

**Comment by mmarkelov** [comment]
@avizuber youp! sure

**Comment by avizuber** [comment]
thanks, @mmarkelov, you're a saint!

@fritz-c / @wuweiweiwu can this get reviewed/merged, please? the deprecated methods comes up in a few issues in this repo. really appreciate the solid component you guys made, would love the update. thanks for your time!

**Comment by avizuber** [comment]
@fritz-c / @wuweiweiwu eyy, I know life is probably *nuts* right now with the pandemic, just wondering if this repo is still maintained or not so I can make a decision on my own project. Seems like a significant amount of people in the Issues section would like to know. Thanks so much for everything you do!

**Comment by ayush-mandowara-bst** [comment]
Is this going to be fixed? Is there a way to temporarily disable this warning for now?

**Comment by jakezien** [comment]
Bump

**Comment by fritz-c** [comment]
Thank you. This is a great help.

**Pull request merged**
