### PR TITLE
Add visual regression test

### PR DESCRIPTION
**Pull request by Nkemjiks**
Hi everyone, this PR adds visual regression testing using [Applitool](https://applitools.com/) eyes. If you are unfamiliar with Visual Regression testing, here a list of references from Applitools to learn more about it. 

https://applitools.com/docs/topics/overview/overview-visual-testing.html
https://applitools.com/blog/troubleshoot-fix-react-bugs
https://circleci.com/gh/myspivey/lock/6

As an open source tool, this service will be offered to you free with an OSS license. They do offer a generous free tier if you want to get a license now to play around with it. I used Cypress as the browser test harness because Applitools has an SDK for it. 

The process for this testing is the docs site is served using concurrently and the existing design script, then Cypress launches a headless Chrome where it runs the tests. Applitool's SDK then takes DOM snapshots w/ styles (not screenshots) from that headless Chrome and sends them to Applitool's servers where it renders those results in Chrome and Firefox and then takes a screenshot of that result and does its intelligent comparisons against the baseline. The baseline is created the first time you run it. If there's an issue, it'll be reported in CircleCI with an included link directly to Applitool's web app where you can see the visual differences and either accept or reject them or do other cool things like set ignored regions or tweak the matching behavior.

You'll need to create an Applitools account and export `APPLITOOLS_API_KEY=Your_API_Key_Here` in your local environment if you run it locally.

I also included the necessary changes for it to run in your TravisCI setup, all you need to do is add your APPLITOOLS_API_KEY to your TravisCI project environment variables in their UI.

To run the test locally, go to your directory and run:  
`yarn cypress:open
`

### CODE REVIEW

**Comment by wuweiweiwu** [comment]
Thanks for doing this! This is awesome!

Ill figure out why ci is being weird.

**Comment by wuweiweiwu** [comment]
travis ci does not allow fork pull requests to have access to env variables set in travis ci

https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions

perhaps ill find some time to work around this or maybe move to a new ci

**Comment by Nkemjiks** [comment]
Hi @wuweiweiwu , thanks for the reply. Any update on the travis issue?

**Comment by cmwhited** [comment]
Hey @wuweiweiwu, bringing this PR to your attention again. Any luck with the travis ci issue?

**Comment by cmwhited** [comment]
Hey @wuweiweiwu, bringing this PR to your attention again. Any luck with the travis ci issue?

**Comment by cmwhited** [comment]
@wuweiweiwu another ping. any chance we could take a look at this?

**Comment by cmwhited** [comment]
@wuweiweiwu @c00kiemon5ter pinging again

**Comment by cmwhited** [comment]
@wuweiweiwu @c00kiemon5ter another ping. would love to get some eyes on this!

**Comment by cmwhited** [comment]
@wuweiweiwu @c00kiemon5ter just pinging again. Have you had y'all had a chance to take a look at this?

**Comment by cmwhited** [comment]
@fritz-c @wuweiweiwu could we get some eyes on this? would really love to get it merged! Thanks!

**Comment by cmwhited** [comment]
@fritz-c @wuweiweiwu would still love to get this PR merged! thanks!

**Comment by cmwhited** [comment]
@fritz-c @wuweiweiwu pinging again. thanks!

**Pull request closed without merging**
