### PR TITLE
Allow Custom Content

### PR DESCRIPTION
**Pull request by agiangrant**
This PR enables the use of custom content to take the place of an image source. This is incredible useful for display youtube videos, video files, PDFs, and placeholder elements.

Prop validation checks to see if mainSrc or mainCustomContent is given. One or the other must exist.

Custom content props are used as a fallback. If the src props are defined, then the custom content props are ignored.

### CODE REVIEW

**Comment by crobinson42** [comment]
+1 bump! This would be awesome!

**Comment by tb** [comment]
@fritz-c This is great PR, incredible useful for display youtube videos, video files, PDFs, and placeholder elements. Can you take a look?

**Comment by caseykey** [comment]
@fritz-c This is great, could you merge it?

**Comment by iamsaurabhgupt** [comment]
+1 we would love this @fritz-c .
Please prioritise.

**Review by maarten00 — APPROVED** [review]

**Comment by jackson-sandland** [comment]
Bueller?

**Comment by iamsaurabhgupt** [comment]
@fritz-c @wuweiweiwu anything remaining on this? please merge if all looks fine.

**Comment by jadczakd** [comment]
+1 on this one, such a simple way to do a lot :)

**Comment by oxorp** [comment]
We'd love to see a merge too. Currently running our own forked version with these changes and it's great. 
Allows us to serve our users all kinds of assets on our platform in a way that they're already familiar with.

**Comment by sntk** [comment]
Any updates on getting this merged? We'd really appreciate it! @andrew-giangrant you are the man!

**Comment by jugglingjsons** [comment]
Ping - I would also love to see this merged in. Forking own version for now.

**Comment by leilahbirchall** [comment]
Any update on this being merged in? :)

**Comment by symbianm** [comment]
Still, unmerged? +1 need this feature

**Comment by chris-oms** [comment]
+1 Please merge!

**Comment by vincent-scw** [comment]
Please merge! Thanks!

**Comment by oosharma** [comment]
Please merge.

**Comment by anjanvb** [comment]
This PR will be super helpful. Please Merge.

**Pull request closed without merging**
