### PR TITLE
Make component React strict mode ready.

### PR DESCRIPTION
**Pull request by webcarrot**
Add getDerivedStateFromProps
Convert some functions and move it to utils. 

Require React 16.3

Benefits? - allow:
<React.unstable_AsyncMode> / <React.StrictMode> without warnings.

This is fast refactoring - tests probably should be updated.

### CODE REVIEW

**Comment by webcarrot** [comment]
@wuweiweiwu 
I add **React Compatibility** section in README.

I think adding optional polyfill as dependency for a package is a bad idea - many packages already drop support for old React versions.

Sorry for my English.

**Comment by webcarrot** [comment]
@wuweiweiwu
Please give me a reply.

**Comment by wuweiweiwu** [comment]
Hi @webcarrot I'll try to review this more thoroughly when I have time! Thanks for your patience!

**Comment by webcarrot** [comment]
This code is/will be outdated. close then.

**Pull request closed without merging**
