### PR TITLE
Implement zoomMinLevel and zoomMaxLevel props

### PR DESCRIPTION
**Pull request by Horat1us**

### CODE REVIEW

**Comment by fritz-c** [comment]
Thank you for the contribution. I don't see the point of the zoomMinLevel prop - you are zoomed in by default?

**Comment by Horat1us** [comment]
https://github.com/Horat1us/react-image-lightbox-rotate
has bug, when zooming should not be disabled after 90˚ rotation. It can be only fixed if react-image-lightbox be able to take zoomMinLevel.

Should I fix snapshot?

**Comment by Horat1us** [comment]
What about this pull request? I really need it ;)

**Comment by wuweiweiwu** [comment]
I don't think this is a feature we want to implement on our side.

**Pull request closed without merging**
