### PR TITLE
Reset didUnmount flag when component is mounted

### LINKED ISSUE #589: Loading icon gets stuck in React 18 dev mode
I ran into this issue in React 18 app using strict mode.

The lightbox never shows the first image, but instead, it keeps showing a loading icon. The images start showing fine only after I click the previous/next buttons.

Screen Shot 2022-03-31 at 7 28 43 PM

Demo: https://codesandbox.io/s/github/igordanchenko/react-photo-album/tree/v1.12.0/examples/lightbox

Steps to reproduce:
1. Open the above link
2. Click any image

This issue is related to the following change in React 18:

> React 18 introduces a new development-only check to Strict Mode. This new check will automatically unmount and remount every component, whenever a component mounts for the first time, restoring the previous state on the second mount.

https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-strict-mode

While this bug is currently visible only in dev mode, it highlights that similar issues may occur in production in the future.

### PR DESCRIPTION
**Pull request by igordanchenko**
This PR addresses the issue described in #589 

Closes #589

### CODE REVIEW

**Comment by nvmnghia** [comment]
This seems to be awfully good & easy, compared to #632. Can you explain?

**Comment by igordanchenko** [comment]
This PR addresses a very specific bug in the library that manifests itself in React 18 strict mode. The other ticket you mention aims to address a completely different issue, so I’m not sure how to compare these two PRs.

**Comment by nvmnghia** [comment]
@igordanchenko no the other issue also fix #589. 

Is there anywhere can I read more about your fix?

**Comment by igordanchenko** [comment]
@nvmnghia, #632 doesn't fix the underlying issue described in #589, it's just hiding the most obvious symptom. In fact, #632 breaks the lightbox in React 18 strict mode as the lightbox can be opened only once, and won't open again once closed.

You can read about React 18 strict mode component lifecycle changes [here](https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-strict-mode).

**Pull request closed without merging**
